apiVersion: v1
kind: Service
metadata:
  name: nodulapi-nodeport
  labels:
    app.kubernetes.io/name: nodulapp
    app.kubernetes.io/component: nodulapi
spec:
  type: NodePort
  ports:
    - name: http
      port: 3333
      targetPort: 5959
      nodePort: 31111
  selector:
    app.kubernetes.io/component: nodulapi
