apiVersion: v1
kind: Service
metadata:
  name: nodulapi-nodeport
  labels:
    label.app: nodulapp
    label.component: nodulapi
    label.object: nodulapi-nodeport
spec:
  type: NodePort
  ports:
    - name: http
      port: 3333
      targetPort: 5959
      nodePort: 31111
  selector:
    label.object: nodulapi-pod
