apiVersion: v1
kind: Service
metadata:
  name: nodulfront-nodeport
  labels:
    label.app: nodulapp
    label.component: nodulfront
    label.object: nodulfront-nodeport
spec:
  type: NodePort
  ports:
    - name: http
      port: 3334
      targetPort: 7474
      nodePort: 32222
  selector:
    label.object: nodulfront-pod
