apiVersion: v1
kind: Service
metadata:
  name: nodulfront-nodeport
  labels:
    app: nodulapp
    component: nodulfront
spec:
  type: NodePort
  ports:
    - name: http
      port: 3334
      targetPort: 7474
      nodePort: 32222
  selector:
    component: nodulfront
