apiVersion: v1
kind: Pod
metadata:
  name: nodulapi-pod
  labels:
    label.app: nodulapp
    label.component: nodulapi
    label.object: nodulapi-pod

spec:
  volumes:
    - name: file-storage
      emptyDir: {}
    # - name: redis-storage
    #   emptyDir: {}
    - name: mongo-storage
      emptyDir: {}

  containers:

    - name: nodulapi
      image: dnrjpc/nodulapi:1
      #imagePullPolicy: Always
      imagePullPolicy: Never
      env:
        - name: NODUL_API_PORT
          value: "5959"
        - name: NODUL_FOO
          value: This is a message from k8s
        # - name: NODUL_USE_REDIS
        #   value: "1"
        # - name: NODUL_REDIS_HOST
        #   value: 127.0.0.1
        - name: NODUL_USE_MONGO
          value: "1"
        - name: NODUL_MONGO_HOST
          value: 127.0.0.1
      ports:
        - containerPort: 5959
      volumeMounts:
        - name: file-storage
          mountPath: /tmp/nodulapp

    # - name: nodulredis
    #   image: redis:6-alpine
    #   volumeMounts:
    #     - name: redis-storage
    #       mountPath: /data

    - name: nodulmongo
      image: mongo:4.4.6
      volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
