apiVersion: v1
kind: Service
metadata:
  name: mongo-clusterip
  labels:
    label.app: nodulapp
    label.component: mongo
spec:
  type: ClusterIP
  selector:
    label.object: mongo-pod
  ports:
    - port: 27017
      targetPort: 27017
