apiVersion: v1
kind: Service
metadata:
  name: mongo-clusterip
  labels:
    app: nodulapp
    component: mongo
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017
