apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodulfront-deployment
  labels:
    label.app: nodulapp
    label.component: nodulfront
    label.object: nodulfront-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      label.object: nodulfront-pod
  template:
    metadata:
      labels:
        label.app: nodulapp
        label.component: nodulfront
        label.object: nodulfront-pod
    spec:
      containers:
        - name: nodulfront
          image: dnrjpc/nodulfront:1
          env:
            - name: NODUL_API_URL
              value: http://127.0.0.1/api
          ports:
            - containerPort: 7474
