apiVersion: v1
kind: Service
metadata:
  name: nodulapi-clusterip
  labels:
    label.app: nodulapp
    label.component: nodulapi
spec:
  type: ClusterIP
  selector:
    label.object: nodulapi-pod
  ports:
    - port: 6363
      targetPort: 3000
