apiVersion: v1
kind: Service
metadata:
  name: nodulfront-clusterip
  labels:
    app: nodulapp
    component: nodulfront
spec:
  type: ClusterIP
  selector:
    component: nodulfront
  ports:
    - port: 7171
      targetPort: 4000
