apiVersion: v1
kind: Service
metadata:
  name: nodulfront-clusterip
  labels:
    app.kubernetes.io/name: nodulapp
    app.kubernetes.io/component: nodulfront
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: nodulfront
  ports:
    - port: 7171
      targetPort: 4000
