apiVersion: v1
kind: Service
metadata:
  name: nodulapi-clusterip
  labels:
    app: nodulapp
    component: nodulapi
spec:
  type: ClusterIP
  selector:
    component: nodulapi
  ports:
    - port: 6363
      targetPort: 3000
