apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  labels:
    label.app: nodulapp
    label.component: redis
spec:
  type: ClusterIP
  selector:
    label.object: redis-pod
  ports:
    - port: 6379
      targetPort: 6379
