apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodulapi-pvc
  labels:
    label.app: nodulapp
    label.component: nodulapi
    label.object: nodulapi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    label.app: nodulapp
    label.component: redis
    label.object: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    label.app: nodulapp
    label.component: mongo
    label.object: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
