apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodulapi-pvc
  labels:
    app.kubernetes.io/name: nodulapp
    app.kubernetes.io/component: nodulapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app.kubernetes.io/name: nodulapp
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app.kubernetes.io/name: nodulapp
    app.kubernetes.io/component: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
