services:
  nodulapi:
    build:
      context: ../../app
      dockerfile: api.dockerfile
    container_name: nodulapi
    ports:
      - 8585:3000
    volumes:
      - ../../data/file:/tmp/nodulapp
    environment:
      # NODUL_USE_REDIS: 1
      NODUL_USE_MONGO: 1
      NODUL_FOO: This is a message from docker compose
      NODUL_REDIS_HOST: nodulredis
      NODUL_MONGO_HOST: nodulmongo
    depends_on:
      - redis

  # redis:
  #   image: redis:6-alpine
  #   container_name: nodulredis
  #   volumes:
  #     - ../../data/redis:/data

  mongodb:
    image: mongo:4.4.6
    container_name: nodulmongo
    volumes:
      - ../../data/mongodb:/data/db

  nodulfront:
    build:
      context: ../../app
      dockerfile: front.dockerfile
    container_name: nodulfront
    ports:
      - 8090:4000
    environment:
      NODUL_API_URL: http://localhost:8585
    depends_on:
      - nodulapi
